# Brazil E-Commerce Analysis

## 1. Project Overview

### Project Scope

This project examines a Brazilian e-commerce marketplace through sales, customer, product, seller, payment, delivery, review, and regional performance data. It connects these perspectives to provide a structured view of commercial activity and the end-to-end customer journey.

### Project Motivation

The project was created to demonstrate how marketplace transaction data can be transformed into actionable business insight. Its purpose is to identify opportunities related to growth, operational efficiency, and customer experience through a practical e-commerce analytics workflow.

## 2. Business Objectives

This project analyzes macro-level Brazilian e-commerce performance and marketplace trends. It examines market share proxies, brand and product categories, company competitiveness, and customer purchasing power to identify the commercial and operational factors that shape marketplace performance.

The analysis focuses on order volume, revenue, delivery, customer behavior, seller performance, category performance, payment patterns, and customer reviews. Market share and competitive position are evaluated within the available marketplace data using seller- and category-level measures.

## 3. Dataset Overview

### 3.1 Data Sources

The analysis uses nine CSV files from the Olist Brazilian E-Commerce dataset. Together, they describe the order lifecycle, customer and seller locations, products, payments, reviews, and geographic reference data.

| Source File                             | Grain                                    | Main Purpose                                                      |
| --------------------------------------- | ---------------------------------------- | ----------------------------------------------------------------- |
| `olist_orders_dataset.csv`              | One row per order                        | Order status and order lifecycle timestamps.                      |
| `olist_order_items_dataset.csv`         | One row per item within an order         | Item price, freight charge, product, and seller information.      |
| `olist_order_payments_dataset.csv`      | One row per payment record               | Payment method, installment count, and payment value.             |
| `olist_order_reviews_dataset.csv`       | One row per customer review              | Customer rating, review text, and response timestamps.            |
| `olist_customers_dataset.csv`           | One row per customer-order record        | Customer identity and location attributes.                        |
| `olist_products_dataset.csv`            | One row per product                      | Product category and physical product attributes.                 |
| `olist_sellers_dataset.csv`             | One row per seller                       | Seller identity and location attributes.                          |
| `olist_geolocation_dataset.csv`         | One row per geographic coordinate record | Postal-code, city, state, latitude, and longitude reference data. |
| `product_category_name_translation.csv` | One row per product category translation | Portuguese-to-English category mapping.                           |

### 3.2 Data Model and Relationships

The `olist_orders_dataset.csv` file is the central transaction table. It connects each order to the customer, item, payment, and review records needed for marketplace analysis.

| From File                          | Join Key                   | To File                                 | Relationship                                                       |
| ---------------------------------- | -------------------------- | --------------------------------------- | ------------------------------------------------------------------ |
| `olist_orders_dataset.csv`         | `customer_id`              | `olist_customers_dataset.csv`           | Each order links to one customer-order record.                     |
| `olist_order_items_dataset.csv`    | `order_id`                 | `olist_orders_dataset.csv`              | An order can contain multiple item records.                        |
| `olist_order_payments_dataset.csv` | `order_id`                 | `olist_orders_dataset.csv`              | An order can have one or more payment records.                     |
| `olist_order_reviews_dataset.csv`  | `order_id`                 | `olist_orders_dataset.csv`              | An order can be linked to one or more review records.              |
| `olist_order_items_dataset.csv`    | `product_id`               | `olist_products_dataset.csv`            | Each item links to one product.                                    |
| `olist_order_items_dataset.csv`    | `seller_id`                | `olist_sellers_dataset.csv`             | Each item links to one seller.                                     |
| `olist_products_dataset.csv`       | `product_category_name`    | `product_category_name_translation.csv` | Product categories can be translated from Portuguese to English.   |
| `olist_customers_dataset.csv`      | `customer_zip_code_prefix` | `olist_geolocation_dataset.csv`         | Customer locations can be enriched with geographic reference data. |
| `olist_sellers_dataset.csv`        | `seller_zip_code_prefix`   | `olist_geolocation_dataset.csv`         | Seller locations can be enriched with geographic reference data.   |

The geolocation file may contain multiple coordinate records for the same postal-code prefix. Geographic analysis should therefore aggregate this file to one representative location per postal-code prefix before joining it to customer or seller records.

### 3.3 Data Dictionary

#### `olist_customers_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `customer_id` | Text | Identifier for the customer record associated with an order. |
| `customer_unique_id` | Text | Persistent identifier for an individual customer across multiple orders. |
| `customer_zip_code_prefix` | Text | Customer postal-code prefix. |
| `customer_city` | Text | Customer city. |
| `customer_state` | Text | Customer state in Brazil. |

**Dataset of customers' information such as id and geolocations.**

#### `olist_geolocation_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `geolocation_zip_code_prefix` | Text | Postal-code prefix used to locate the geographic record. |
| `geolocation_lat` | Decimal | Latitude of the geographic record. |
| `geolocation_lng` | Decimal | Longitude of the geographic record. |
| `geolocation_city` | Text | City associated with the geographic record. |
| `geolocation_state` | Text | Brazilian state associated with the geographic record. |

**Dataset of geolocation positioning.**

#### `olist_order_items_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `order_id` | Text | Identifier of the order containing the item. |
| `order_item_id` | Integer | Sequential number of the item within an order. |
| `product_id` | Text | Identifier of the purchased product. |
| `seller_id` | Text | Identifier of the seller fulfilling the item. |
| `shipping_limit_date` | DateTime | Deadline for the seller to hand the item to the logistics partner. |
| `price` | Decimal | Item price charged to the customer. |
| `freight_value` | Decimal | Freight charge assigned to the order item. |

**Dataset of basic items' selling informations.**

#### `olist_order_payments_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `order_id` | Text | Identifier of the order associated with the payment. |
| `payment_sequential` | Integer | Sequence number for a payment within an order. |
| `payment_type` | Text | Payment method used by the customer. |
| `payment_installments` | Integer | Number of installments selected for the payment. |
| `payment_value` | Decimal | Total monetary value of the payment record. |

**Dataset of orders' paying meathods and amounts.**

#### `olist_order_reviews_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `review_id` | Text | Unique identifier for a customer review. |
| `order_id` | Text | Identifier of the order reviewed by the customer. |
| `review_score` | Integer | Customer satisfaction rating, typically on a five-point scale. |
| `review_comment_title` | Text | Title supplied by the customer for the review. |
| `review_comment_message` | Text | Written comment supplied by the customer. |
| `review_creation_date` | DateTime | Date and time when the customer created the review. |
| `review_answer_timestamp` | DateTime | Date and time when the marketplace responded to the review. |

**Dataset of orders' reviews' rattings, comments and timestamps.**

#### `olist_orders_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `order_id` | Text | Unique identifier for an order. |
| `customer_id` | Text | Identifier of the customer record linked to the order. |
| `order_status` | Text | Current operational status of the order. |
| `order_purchase_timestamp` | DateTime | Date and time when the customer placed the order. |
| `order_approved_at` | DateTime | Date and time when the payment or order approval was completed. |
| `order_delivered_carrier_date` | DateTime | Date and time when the carrier received the order. |
| `order_delivered_customer_date` | DateTime | Date and time when the customer received the order. |
| `order_estimated_delivery_date` | DateTime | Estimated delivery date communicated for the order. |

**Dataset of orders' lifecycle infos.**

#### `olist_products_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `product_id` | Text | Unique identifier for a product. |
| `product_category_name` | Text | Product category label in Portuguese. |
| `product_name_lenght` | Integer | Number of characters in the product name. |
| `product_description_lenght` | Integer | Number of characters in the product description. |
| `product_photos_qty` | Integer | Number of product photographs available. |
| `product_weight_g` | Decimal | Product weight in grams. |
| `product_length_cm` | Decimal | Product length in centimeters. |
| `product_height_cm` | Decimal | Product height in centimeters. |
| `product_width_cm` | Decimal | Product width in centimeters. |

**Dataset of online products infos.**

#### `olist_sellers_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `seller_id` | Text | Unique identifier for a marketplace seller. |
| `seller_zip_code_prefix` | Text | Seller postal-code prefix. |
| `seller_city` | Text | Seller city. |
| `seller_state` | Text | Seller state in Brazil. |

**Dataset of sellers' infos.**

#### `product_category_name_translation.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `product_category_name` | Text | Original Portuguese product category label. |
| `product_category_name_english` | Text | English translation of the product category label. |

**Dataset of product categories' English translations.**

## 4. Data Preparation

### 4.1 Environment Setup

In [16]:
import duckdb
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from IPython.display import display
from pathlib import Path

DATA_DIR = Path("source_data")

### 4.2 Data Loading

In [17]:
customers_file = 'olist_customers_dataset.csv'
geolocation_file = 'olist_geolocation_dataset.csv'
items_file = 'olist_order_items_dataset.csv'
payments_file = 'olist_order_payments_dataset.csv'
reviews_file = 'olist_order_reviews_dataset.csv'
orders_file = 'olist_orders_dataset.csv'
products_file = 'olist_products_dataset.csv'
sellers_file = 'olist_sellers_dataset.csv'
translation_file = 'product_category_name_translation.csv'

files = [
    customers_file,
    geolocation_file,
    items_file,
    payments_file,
    reviews_file,
    orders_file,
    products_file,
    sellers_file,
    translation_file]

### 4.3 Data Quality Assessment

In [18]:
quality_results = []

for _ in files:
    df = pd.read_csv(DATA_DIR / _)
    
    total_row = df.shape[0]
    total_cells = df.shape[0]*df.shape[1]
    
    nulls = df.isnull().sum().sum()
    duplicates = df.duplicated().sum()
    
    missing_rate = nulls / total_cells if total_cells > 0 else 0
    duplicate_rate = duplicates / total_row if total_row > 0 else 0

    quality_results.append({
        "Dataset":_,
        "Total Rows": total_row,
        "Columns": df.shape[1],
        "Missing Values": nulls,
        "Missing Rate": missing_rate,
        "Duplicate Rows": duplicates,
        "Duplicate Rate":duplicate_rate
    })
    
quality_summary = pd.DataFrame(quality_results)

quality_summary['Missing Rate'] = quality_summary["Missing Rate"].map(lambda value:f"{value:.2%}")
quality_summary['Duplicate Rate'] = quality_summary['Duplicate Rate'].map(lambda value:f"{value:.2%}")

display(quality_summary)

,Dataset,Total Rows,Columns,Missing Values,Missing Rate,Duplicate Rows,Duplicate Rate
0,olist_customers_dataset.csv,99441,5,0,0.00%,0,0.00%
1,olist_geolocation_dataset.csv,1000163,5,0,0.00%,261831,26.18%
2,olist_order_items_dataset.csv,112650,7,0,0.00%,0,0.00%
3,olist_order_payments_dataset.csv,103886,5,0,0.00%,0,0.00%
4,olist_order_reviews_dataset.csv,99224,7,145903,21.01%,0,0.00%
5,olist_orders_dataset.csv,99441,8,4908,0.62%,0,0.00%
6,olist_products_dataset.csv,32951,9,2448,0.83%,0,0.00%
7,olist_sellers_dataset.csv,3095,4,0,0.00%,0,0.00%
8,product_category_name_translation.csv,71,2,0,0.00%,0,0.00%

For missing elements in reviews sheet are reasonable since not everyone leaves a review after buying a product, but missing elements in orders and products sheets are not as for every elements in these sheets are essential and indispensable.
For duplicate elements in geolocation sheet are also quite not reasonable since the exact same rows have no additional meanings so those could be cleaned.

### 4.4 Data Cleaning

In [19]:
file_map = {
    "customers_df": "olist_customers_dataset.csv",
    "geolocation_df": "olist_geolocation_dataset.csv",
    "items_df": "olist_order_items_dataset.csv",
    "payments_df": "olist_order_payments_dataset.csv",
    "reviews_df": "olist_order_reviews_dataset.csv",
    "orders_df": "olist_orders_dataset.csv",
    "products_df": "olist_products_dataset.csv",
    "sellers_df": "olist_sellers_dataset.csv",
    "translation_df": "product_category_name_translation.csv",
}

dfs: dict[str, pd.DataFrame] = {}

for df_name, file_name in file_map.items():
    dfs[df_name] = pd.read_csv(DATA_DIR / file_name)

In [20]:
quality_results = []

for df_name, df in dfs.items():
    total_rows = df.shape[0]
    total_columns = df.shape[1]
    total_cells = total_rows * total_columns

    missing_values = df.isnull().sum().sum()
    duplicate_rows = df.duplicated().sum()

    missing_rate = (
        missing_values / total_cells
        if total_cells > 0
        else 0
    )

    duplicate_rate = (
        duplicate_rows / total_rows
        if total_rows > 0
        else 0
    )

    quality_results.append({
        "Dataframe": df_name,
        "Rows": total_rows,
        "Columns": total_columns,
        "Missing Values": missing_values,
        "Missing Rate": missing_rate,
        "Duplicate Rows": duplicate_rows,
        "Duplicate Rate": duplicate_rate,
    })

quality_summary = pd.DataFrame(quality_results)

quality_summary["Missing Rate"] = quality_summary["Missing Rate"].map(
    lambda value: f"{value:.2%}"
)

quality_summary["Duplicate Rate"] = quality_summary["Duplicate Rate"].map(
    lambda value: f"{value:.2%}"
)

display(quality_summary)

,Dataframe,Rows,Columns,Missing Values,Missing Rate,Duplicate Rows,Duplicate Rate
0,customers_df,99441,5,0,0.00%,0,0.00%
1,geolocation_df,1000163,5,0,0.00%,261831,26.18%
2,items_df,112650,7,0,0.00%,0,0.00%
3,payments_df,103886,5,0,0.00%,0,0.00%
4,reviews_df,99224,7,145903,21.01%,0,0.00%
5,orders_df,99441,8,4908,0.62%,0,0.00%
6,products_df,32951,9,2448,0.83%,0,0.00%
7,sellers_df,3095,4,0,0.00%,0,0.00%
8,translation_df,71,2,0,0.00%,0,0.00%

In [21]:
customers_df = dfs["customers_df"]
geolocation_df = dfs["geolocation_df"]
items_df = dfs["items_df"]
payments_df = dfs["payments_df"]
reviews_df = dfs["reviews_df"]
orders_df = dfs["orders_df"]
products_df = dfs["products_df"]
sellers_df = dfs["sellers_df"]
translation_df = dfs["translation_df"]

### 4.5 Feature Engineering

In [ ]:
# Customers Features
customers_df["customer_zip_code_prefix"] = customers_df["customer_zip_code_prefix"].astype("string").str.zfill(5)
customers_df["customer_city"] = customers_df["customer_city"].str.strip().str.lower()

"str-lize zip code prefixes and city names."

# Geolocation Features
geolocation_df["geolocation_zip_code_prefix"] = geolocation_df["geolocation_zip_code_prefix"].astype("string").str.zfill(5)
geolocation_df["geolocation_lat"] = pd.to_numeric(geolocation_df["geolocation_lat"], errors="coerce")
geolocation_df["geolocation_lng"] = pd.to_numeric(geolocation_df["geolocation_lng"], errors="coerce")

"numerilize geolocation's lat and lng values."

# Order Item Features
items_df["shipping_limit_date"] = pd.to_datetime(items_df["shipping_limit_date"], errors="coerce")
items_df["price"] = pd.to_numeric(items_df["price"], errors="coerce")
items_df["freight_value"] = pd.to_numeric(items_df["freight_value"], errors="coerce")
items_df["item_total_value"] = items_df["price"] + items_df["freight_value"]

"normalize timestamps and numerilize values."

# Payment Features
payments_df["payment_value"] = pd.to_numeric(payments_df["payment_value"], errors="coerce")
payments_df["payment_installments"] = pd.to_numeric(payments_df["payment_installments"], errors="coerce")

"numerilize values"

# Review Features
reviews_df["review_creation_date"] = pd.to_datetime(reviews_df["review_creation_date"], errors="coerce")
reviews_df["review_answer_timestamp"] = pd.to_datetime(reviews_df["review_answer_timestamp"], errors="coerce")
reviews_df["review_score"] = pd.to_numeric(reviews_df["review_score"], errors="coerce")

"normalize timestamps and numerilize review scores."

# Order Features
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]
for column in date_columns:
    orders_df[column] = pd.to_datetime(orders_df[column], errors="coerce")
orders_df["purchase_year"] = orders_df["order_purchase_timestamp"].dt.year
orders_df["purchase_month"] = orders_df["order_purchase_timestamp"].dt.to_period("M").astype("string")
orders_df["delivery_days"] = (orders_df["order_delivered_customer_date"] - orders_df["order_purchase_timestamp"]).dt.total_seconds() / 86400
orders_df["delivery_delay_days"] = (orders_df["order_delivered_customer_date"] - orders_df["order_estimated_delivery_date"]).dt.total_seconds() / 86400
orders_df["is_late_delivery"] = orders_df["delivery_delay_days"] > 0

"slice timestamps by year, month and day, creating new features."

# Product Features
products_df["product_category_name"] = products_df["product_category_name"].str.strip().str.lower()
product_numeric_columns = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm",
]
for column in product_numeric_columns:
    products_df[column] = pd.to_numeric(products_df[column], errors="coerce")

"numerilize products' parameters."

# Seller Features
sellers_df["seller_zip_code_prefix"] = sellers_df["seller_zip_code_prefix"].astype("string").str.zfill(5)
sellers_df["seller_city"] = sellers_df["seller_city"].str.strip().str.lower()

"str-lize zip codes and city names."

""

''

## 5. Exploratory Data Analysis

### 5.1 Sales Performance

### 5.2 Order Status Analysis

### 5.3 Customer Analysis

### 5.4 Product and Category Analysis

### 5.5 Seller Performance Analysis

### 5.6 Payment Behavior Analysis

### 5.7 Delivery and Logistics Analysis

### 5.8 Customer Review Analysis

### 5.9 Geographic Analysis

## 6. Customer Segmentation

### 6.1 RFM Analysis

### 6.2 Repeat Purchase Analysis

### 6.3 Customer Value Analysis

## 7. Customer Experience and Delivery Drivers

### 7.1 Delivery Time and Review Score

### 7.2 Freight Cost and Customer Satisfaction

### 7.3 Late Delivery Analysis

### 7.4 Low-Score Order Analysis

## 8. Key Findings

## 9. Business Recommendations

## 10. Limitations

## 11. Conclusion

## 12. Appendix