# Brazil E-Commerce Analysis

## 1. Project Overview

### Project Scope

This project examines a Brazilian e-commerce marketplace through sales, customer, product, seller, payment, delivery, review, and regional performance data. It connects these perspectives to provide a structured view of commercial activity and the end-to-end customer journey.

### Project Motivation

The project was created to demonstrate how marketplace transaction data can be transformed into actionable business insight. Its purpose is to identify opportunities related to growth, operational efficiency, and customer experience through a practical e-commerce analytics workflow.

## 2. Business Objectives

This project analyzes macro-level Brazilian e-commerce performance and marketplace trends. It examines market share proxies, brand and product categories, company competitiveness, and customer purchasing power to identify the commercial and operational factors that shape marketplace performance.

The analysis focuses on order volume, revenue, delivery, customer behavior, seller performance, category performance, payment patterns, and customer reviews. Market share and competitive position are evaluated within the available marketplace data using seller- and category-level measures.

## 3. Dataset Overview

### 3.1 Data Sources

The analysis uses nine CSV files from the Olist Brazilian E-Commerce dataset. Together, they describe the order lifecycle, customer and seller locations, products, payments, reviews, and geographic reference data.

| Source File                             | Grain                                    | Main Purpose                                                      |
| --------------------------------------- | ---------------------------------------- | ----------------------------------------------------------------- |
| `olist_orders_dataset.csv`              | One row per order                        | Order status and order lifecycle timestamps.                      |
| `olist_order_items_dataset.csv`         | One row per item within an order         | Item price, freight charge, product, and seller information.      |
| `olist_order_payments_dataset.csv`      | One row per payment record               | Payment method, installment count, and payment value.             |
| `olist_order_reviews_dataset.csv`       | One row per customer review              | Customer rating, review text, and response timestamps.            |
| `olist_customers_dataset.csv`           | One row per customer-order record        | Customer identity and location attributes.                        |
| `olist_products_dataset.csv`            | One row per product                      | Product category and physical product attributes.                 |
| `olist_sellers_dataset.csv`             | One row per seller                       | Seller identity and location attributes.                          |
| `olist_geolocation_dataset.csv`         | One row per geographic coordinate record | Postal-code, city, state, latitude, and longitude reference data. |
| `product_category_name_translation.csv` | One row per product category translation | Portuguese-to-English category mapping.                           |

### 3.2 Data Model and Relationships

The `olist_orders_dataset.csv` file is the central transaction table. It connects each order to the customer, item, payment, and review records needed for marketplace analysis.

| From File                          | Join Key                   | To File                                 | Relationship                                                       |
| ---------------------------------- | -------------------------- | --------------------------------------- | ------------------------------------------------------------------ |
| `olist_orders_dataset.csv`         | `customer_id`              | `olist_customers_dataset.csv`           | Each order links to one customer-order record.                     |
| `olist_order_items_dataset.csv`    | `order_id`                 | `olist_orders_dataset.csv`              | An order can contain multiple item records.                        |
| `olist_order_payments_dataset.csv` | `order_id`                 | `olist_orders_dataset.csv`              | An order can have one or more payment records.                     |
| `olist_order_reviews_dataset.csv`  | `order_id`                 | `olist_orders_dataset.csv`              | An order can be linked to one or more review records.              |
| `olist_order_items_dataset.csv`    | `product_id`               | `olist_products_dataset.csv`            | Each item links to one product.                                    |
| `olist_order_items_dataset.csv`    | `seller_id`                | `olist_sellers_dataset.csv`             | Each item links to one seller.                                     |
| `olist_products_dataset.csv`       | `product_category_name`    | `product_category_name_translation.csv` | Product categories can be translated from Portuguese to English.   |
| `olist_customers_dataset.csv`      | `customer_zip_code_prefix` | `olist_geolocation_dataset.csv`         | Customer locations can be enriched with geographic reference data. |
| `olist_sellers_dataset.csv`        | `seller_zip_code_prefix`   | `olist_geolocation_dataset.csv`         | Seller locations can be enriched with geographic reference data.   |

The geolocation file may contain multiple coordinate records for the same postal-code prefix. Geographic analysis should therefore aggregate this file to one representative location per postal-code prefix before joining it to customer or seller records.

### 3.3 Data Dictionary

#### `olist_customers_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `customer_id` | Text | Identifier for the customer record associated with an order. |
| `customer_unique_id` | Text | Persistent identifier for an individual customer across multiple orders. |
| `customer_zip_code_prefix` | Text | Customer postal-code prefix. |
| `customer_city` | Text | Customer city. |
| `customer_state` | Text | Customer state in Brazil. |

**Dataset of customers' information such as id and geolocations.**

#### `olist_geolocation_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `geolocation_zip_code_prefix` | Text | Postal-code prefix used to locate the geographic record. |
| `geolocation_lat` | Decimal | Latitude of the geographic record. |
| `geolocation_lng` | Decimal | Longitude of the geographic record. |
| `geolocation_city` | Text | City associated with the geographic record. |
| `geolocation_state` | Text | Brazilian state associated with the geographic record. |

**Dataset of geolocation positioning.**

#### `olist_order_items_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `order_id` | Text | Identifier of the order containing the item. |
| `order_item_id` | Integer | Sequential number of the item within an order. |
| `product_id` | Text | Identifier of the purchased product. |
| `seller_id` | Text | Identifier of the seller fulfilling the item. |
| `shipping_limit_date` | DateTime | Deadline for the seller to hand the item to the logistics partner. |
| `price` | Decimal | Item price charged to the customer. |
| `freight_value` | Decimal | Freight charge assigned to the order item. |

**Dataset of basic items' selling informations.**

#### `olist_order_payments_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `order_id` | Text | Identifier of the order associated with the payment. |
| `payment_sequential` | Integer | Sequence number for a payment within an order. |
| `payment_type` | Text | Payment method used by the customer. |
| `payment_installments` | Integer | Number of installments selected for the payment. |
| `payment_value` | Decimal | Total monetary value of the payment record. |

**Dataset of orders' paying meathods and amounts.**

#### `olist_order_reviews_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `review_id` | Text | Unique identifier for a customer review. |
| `order_id` | Text | Identifier of the order reviewed by the customer. |
| `review_score` | Integer | Customer satisfaction rating, typically on a five-point scale. |
| `review_comment_title` | Text | Title supplied by the customer for the review. |
| `review_comment_message` | Text | Written comment supplied by the customer. |
| `review_creation_date` | DateTime | Date and time when the customer created the review. |
| `review_answer_timestamp` | DateTime | Date and time when the marketplace responded to the review. |

**Dataset of orders' reviews' rattings, comments and timestamps.**

#### `olist_orders_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `order_id` | Text | Unique identifier for an order. |
| `customer_id` | Text | Identifier of the customer record linked to the order. |
| `order_status` | Text | Current operational status of the order. |
| `order_purchase_timestamp` | DateTime | Date and time when the customer placed the order. |
| `order_approved_at` | DateTime | Date and time when the payment or order approval was completed. |
| `order_delivered_carrier_date` | DateTime | Date and time when the carrier received the order. |
| `order_delivered_customer_date` | DateTime | Date and time when the customer received the order. |
| `order_estimated_delivery_date` | DateTime | Estimated delivery date communicated for the order. |

**Dataset of orders' lifecycle infos.**

#### `olist_products_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `product_id` | Text | Unique identifier for a product. |
| `product_category_name` | Text | Product category label in Portuguese. |
| `product_name_lenght` | Integer | Number of characters in the product name. |
| `product_description_lenght` | Integer | Number of characters in the product description. |
| `product_photos_qty` | Integer | Number of product photographs available. |
| `product_weight_g` | Decimal | Product weight in grams. |
| `product_length_cm` | Decimal | Product length in centimeters. |
| `product_height_cm` | Decimal | Product height in centimeters. |
| `product_width_cm` | Decimal | Product width in centimeters. |

**Dataset of online products infos.**

#### `olist_sellers_dataset.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `seller_id` | Text | Unique identifier for a marketplace seller. |
| `seller_zip_code_prefix` | Text | Seller postal-code prefix. |
| `seller_city` | Text | Seller city. |
| `seller_state` | Text | Seller state in Brazil. |

**Dataset of sellers' infos.**

#### `product_category_name_translation.csv`

| Field | Data Type | Business Meaning |
|---|---|---|
| `product_category_name` | Text | Original Portuguese product category label. |
| `product_category_name_english` | Text | English translation of the product category label. |

**Dataset of product categories' English translations.**

## 4. Data Preparation

### 4.1 Environment Setup

In [1]:
import duckdb
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from IPython.display import display
from pathlib import Path

DATA_DIR = Path("source_data")

### 4.2 Data Loading

In [2]:
customers_file = 'olist_customers_dataset.csv'
geolocation_file = 'olist_geolocation_dataset.csv'
items_file = 'olist_order_items_dataset.csv'
payments_file = 'olist_order_payments_dataset.csv'
reviews_file = 'olist_order_reviews_dataset.csv'
orders_file = 'olist_orders_dataset.csv'
products_file = 'olist_products_dataset.csv'
sellers_file = 'olist_sellers_dataset.csv'
translation_file = 'product_category_name_translation.csv'

files = [
    customers_file,
    geolocation_file,
    items_file,
    payments_file,
    reviews_file,
    orders_file,
    products_file,
    sellers_file,
    translation_file]

### 4.3 Data Quality Assessment

In [3]:
quality_results = []

for _ in files:
    df = pd.read_csv(DATA_DIR / _)
    
    total_row = df.shape[0]
    total_cells = df.shape[0]*df.shape[1]
    
    nulls = df.isnull().sum().sum()
    duplicates = df.duplicated().sum()
    
    missing_rate = nulls / total_cells if total_cells > 0 else 0
    duplicate_rate = duplicates / total_row if total_row > 0 else 0

    quality_results.append({
        "Dataset":_,
        "Total Rows": total_row,
        "Columns": df.shape[1],
        "Missing Values": nulls,
        "Missing Rate": missing_rate,
        "Duplicate Rows": duplicates,
        "Duplicate Rate":duplicate_rate
    })
    
quality_summary = pd.DataFrame(quality_results)

quality_summary['Missing Rate'] = quality_summary["Missing Rate"].map(lambda value:f"{value:.2%}")
quality_summary['Duplicate Rate'] = quality_summary['Duplicate Rate'].map(lambda value:f"{value:.2%}")

display(quality_summary)

,Dataset,Total Rows,Columns,Missing Values,Missing Rate,Duplicate Rows,Duplicate Rate
0,olist_customers_dataset.csv,99441,5,0,0.00%,0,0.00%
1,olist_geolocation_dataset.csv,1000163,5,0,0.00%,261831,26.18%
2,olist_order_items_dataset.csv,112650,7,0,0.00%,0,0.00%
3,olist_order_payments_dataset.csv,103886,5,0,0.00%,0,0.00%
4,olist_order_reviews_dataset.csv,99224,7,145903,21.01%,0,0.00%
5,olist_orders_dataset.csv,99441,8,4908,0.62%,0,0.00%
6,olist_products_dataset.csv,32951,9,2448,0.83%,0,0.00%
7,olist_sellers_dataset.csv,3095,4,0,0.00%,0,0.00%
8,product_category_name_translation.csv,71,2,0,0.00%,0,0.00%

For missing elements in reviews sheet are reasonable since not everyone leaves a review after buying a product, but missing elements in orders and products sheets are not as for every elements in these sheets are essential and indispensable.
For duplicate elements in geolocation sheet are also quite not reasonable since the exact same rows have no additional meanings so those could be cleaned.

### 4.4 Data Cleaning

In [4]:
file_map = {
    "customers_df": "olist_customers_dataset.csv",
    "geolocation_df": "olist_geolocation_dataset.csv",
    "items_df": "olist_order_items_dataset.csv",
    "payments_df": "olist_order_payments_dataset.csv",
    "reviews_df": "olist_order_reviews_dataset.csv",
    "orders_df": "olist_orders_dataset.csv",
    "products_df": "olist_products_dataset.csv",
    "sellers_df": "olist_sellers_dataset.csv",
    "translation_df": "product_category_name_translation.csv",
}

dfs: dict[str, pd.DataFrame] = {}

for df_name, file_name in file_map.items():
    dfs[df_name] = pd.read_csv(DATA_DIR / file_name)

In [5]:
quality_results = []

for df_name, df in dfs.items():
    total_rows = df.shape[0]
    total_columns = df.shape[1]
    total_cells = total_rows * total_columns

    missing_values = df.isnull().sum().sum()
    duplicate_rows = df.duplicated().sum()

    missing_rate = (
        missing_values / total_cells
        if total_cells > 0
        else 0
    )

    duplicate_rate = (
        duplicate_rows / total_rows
        if total_rows > 0
        else 0
    )

    quality_results.append({
        "Dataframe": df_name,
        "Rows": total_rows,
        "Columns": total_columns,
        "Missing Values": missing_values,
        "Missing Rate": missing_rate,
        "Duplicate Rows": duplicate_rows,
        "Duplicate Rate": duplicate_rate,
    })

quality_summary = pd.DataFrame(quality_results)

quality_summary["Missing Rate"] = quality_summary["Missing Rate"].map(
    lambda value: f"{value:.2%}"
)

quality_summary["Duplicate Rate"] = quality_summary["Duplicate Rate"].map(
    lambda value: f"{value:.2%}"
)

display(quality_summary)

,Dataframe,Rows,Columns,Missing Values,Missing Rate,Duplicate Rows,Duplicate Rate
0,customers_df,99441,5,0,0.00%,0,0.00%
1,geolocation_df,1000163,5,0,0.00%,261831,26.18%
2,items_df,112650,7,0,0.00%,0,0.00%
3,payments_df,103886,5,0,0.00%,0,0.00%
4,reviews_df,99224,7,145903,21.01%,0,0.00%
5,orders_df,99441,8,4908,0.62%,0,0.00%
6,products_df,32951,9,2448,0.83%,0,0.00%
7,sellers_df,3095,4,0,0.00%,0,0.00%
8,translation_df,71,2,0,0.00%,0,0.00%

In [6]:
customers_df = dfs["customers_df"]
geolocation_df = dfs["geolocation_df"]
items_df = dfs["items_df"]
payments_df = dfs["payments_df"]
reviews_df = dfs["reviews_df"]
orders_df = dfs["orders_df"]
products_df = dfs["products_df"]
sellers_df = dfs["sellers_df"]
translation_df = dfs["translation_df"]

### 4.5 Feature Engineering

In [7]:
# Customers Features
customers_df["customer_zip_code_prefix"] = customers_df["customer_zip_code_prefix"].astype("string").str.zfill(5)
customers_df["customer_city"] = customers_df["customer_city"].str.strip().str.lower()

"str-lize zip code prefixes and city names."

# Geolocation Features
geolocation_df["geolocation_zip_code_prefix"] = geolocation_df["geolocation_zip_code_prefix"].astype("string").str.zfill(5)
geolocation_df["geolocation_lat"] = pd.to_numeric(geolocation_df["geolocation_lat"], errors="coerce")
geolocation_df["geolocation_lng"] = pd.to_numeric(geolocation_df["geolocation_lng"], errors="coerce")

"numerilize geolocation's lat and lng values."

# Order Item Features
items_df["shipping_limit_date"] = pd.to_datetime(items_df["shipping_limit_date"], errors="coerce")
items_df["price"] = pd.to_numeric(items_df["price"], errors="coerce")
items_df["freight_value"] = pd.to_numeric(items_df["freight_value"], errors="coerce")
items_df["item_total_value"] = items_df["price"] + items_df["freight_value"]

"normalize timestamps and numerilize values."

# Payment Features
payments_df["payment_value"] = pd.to_numeric(payments_df["payment_value"], errors="coerce")
payments_df["payment_installments"] = pd.to_numeric(payments_df["payment_installments"], errors="coerce")

"numerilize values"

# Review Features
reviews_df["review_creation_date"] = pd.to_datetime(reviews_df["review_creation_date"], errors="coerce")
reviews_df["review_answer_timestamp"] = pd.to_datetime(reviews_df["review_answer_timestamp"], errors="coerce")
reviews_df["review_score"] = pd.to_numeric(reviews_df["review_score"], errors="coerce")

"normalize timestamps and numerilize review scores."

# Order Features
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]
for column in date_columns:
    orders_df[column] = pd.to_datetime(orders_df[column], errors="coerce")
orders_df["purchase_year"] = orders_df["order_purchase_timestamp"].dt.year
orders_df["purchase_month"] = orders_df["order_purchase_timestamp"].dt.to_period("M").astype("string")
orders_df["delivery_days"] = (orders_df["order_delivered_customer_date"] - orders_df["order_purchase_timestamp"]).dt.total_seconds() / 86400
orders_df["delivery_delay_days"] = (orders_df["order_delivered_customer_date"] - orders_df["order_estimated_delivery_date"]).dt.total_seconds() / 86400
orders_df["is_late_delivery"] = orders_df["delivery_delay_days"] > 0

"slice timestamps by year, month and day, creating new features."

# Product Features
products_df["product_category_name"] = products_df["product_category_name"].str.strip().str.lower()
product_numeric_columns = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm",
]
for column in product_numeric_columns:
    products_df[column] = pd.to_numeric(products_df[column], errors="coerce")

"numerilize products' parameters."

# Seller Features
sellers_df["seller_zip_code_prefix"] = sellers_df["seller_zip_code_prefix"].astype("string").str.zfill(5)
sellers_df["seller_city"] = sellers_df["seller_city"].str.strip().str.lower()

"str-lize zip codes and city names."

""

''

## 5. Macro Olist Market Analysis

### 5.1 Market GMV, Average Order Value and Order Volume

In [8]:
# Calculate market-scale KPIs from delivered orders
delivered_order_ids = orders_df.loc[
    orders_df["order_status"].eq("delivered"), "order_id"
].unique()

delivered_items = items_df[items_df["order_id"].isin(delivered_order_ids)]
order_volume = len(delivered_order_ids)
gmv = delivered_items["price"].sum()
average_order_value = gmv / order_volume if order_volume else 0
delivered_customers = orders_df.loc[
    orders_df["order_status"].eq("delivered"), ["customer_id"]
].merge(customers_df[["customer_id", "customer_unique_id"]], on="customer_id", how="left")
transacting_customers = delivered_customers["customer_unique_id"].nunique()
active_sellers = delivered_items["seller_id"].nunique()

kpi_figure = go.Figure(
    data=[
        go.Indicator(
            mode="number",
            value=gmv,
            number={"prefix": "R$ ", "valueformat": ",.0f", "font": {"size": 36, "color": "#2563EB"}},
            title={"text": "GMV", "font": {"size": 16}},
            domain={"x": [0.0, 0.30], "y": [0.55, 1]},
        ),
        go.Indicator(
            mode="number",
            value=order_volume,
            number={"valueformat": ",.0f", "font": {"size": 36, "color": "#059669"}},
            title={"text": "Delivered Orders", "font": {"size": 16}},
            domain={"x": [0.35, 0.65], "y": [0.55, 1]},
        ),
        go.Indicator(
            mode="number",
            value=average_order_value,
            number={"prefix": "R$ ", "valueformat": ",.2f", "font": {"size": 36, "color": "#EA580C"}},
            title={"text": "Average Order Value", "font": {"size": 16}},
            domain={"x": [0.70, 1.0], "y": [0.55, 1]},
        ),
        go.Indicator(
            mode="number",
            value=transacting_customers,
            number={"valueformat": ",.0f", "font": {"size": 36, "color": "#7C3AED"}},
            title={"text": "Transacting Customers", "font": {"size": 16}},
            domain={"x": [0.18, 0.45], "y": [0, 0.35]},
        ),
        go.Indicator(
            mode="number",
            value=active_sellers,
            number={"valueformat": ",.0f", "font": {"size": 36, "color": "#DB2777"}},
            title={"text": "Active Sellers", "font": {"size": 16}},
            domain={"x": [0.55, 0.82], "y": [0, 0.35]},
        ),
    ]
)

kpi_figure.update_layout(
    title="Olist Marketplace GMV and Order Scale",
    height=420,
    margin={"l": 30, "r": 30, "t": 70, "b": 30},
)
kpi_figure.show()

### 5.2 Growth Trends and Seasonality

In [9]:
# Build monthly GMV and delivered-order time series
delivered_orders_ts = orders_df.loc[
    orders_df["order_status"].eq("delivered"),
    ["order_id", "order_purchase_timestamp"],
].copy()
delivered_orders_ts["month"] = delivered_orders_ts["order_purchase_timestamp"].dt.to_period("M").dt.to_timestamp()

monthly_orders = (
    delivered_orders_ts.groupby("month", as_index=False)
    .agg(delivered_orders=("order_id", "nunique"))
)
monthly_gmv = (
    items_df.merge(delivered_orders_ts[["order_id", "month"]], on="order_id", how="inner")
    .groupby("month", as_index=False)
    .agg(gmv=("price", "sum"))
)
monthly_market = (
    monthly_orders.merge(monthly_gmv, on="month", how="outer")
    .fillna(0)
    .sort_values("month")
)

# Calculate linear regression trend lines using actual elapsed days
elapsed_days = (monthly_market["month"] - monthly_market["month"].min()).dt.days.to_numpy()
gmv_slope, gmv_intercept = np.polyfit(elapsed_days, monthly_market["gmv"], 1)
orders_slope, orders_intercept = np.polyfit(elapsed_days, monthly_market["delivered_orders"], 1)
monthly_market["gmv_trend"] = gmv_slope * elapsed_days + gmv_intercept
monthly_market["orders_trend"] = orders_slope * elapsed_days + orders_intercept
gmv_r_squared = 1 - ((monthly_market["gmv"] - monthly_market["gmv_trend"]) ** 2).sum() / ((monthly_market["gmv"] - monthly_market["gmv"].mean()) ** 2).sum()
orders_r_squared = 1 - ((monthly_market["delivered_orders"] - monthly_market["orders_trend"]) ** 2).sum() / ((monthly_market["delivered_orders"] - monthly_market["delivered_orders"].mean()) ** 2).sum()
label_index = max(len(monthly_market) - 4, 0)
orders_axis_max = monthly_market["delivered_orders"].max() * 1.4

# Plot monthly GMV and delivered orders with dual Y-axes and regression lines
growth_figure = go.Figure()
growth_figure.add_trace(
    go.Scatter(
        x=monthly_market["month"],
        y=monthly_market["gmv"],
        mode="lines",
        name="GMV",
        line={"color": "#2563EB", "width": 3},
    )
)
growth_figure.add_trace(
    go.Scatter(
        x=monthly_market["month"],
        y=monthly_market["gmv_trend"],
        mode="lines",
        name="GMV Regression Trend",
        line={"color": "#93C5FD", "width": 2, "dash": "dash"},
    )
)
growth_figure.add_trace(
    go.Scatter(
        x=monthly_market["month"],
        y=monthly_market["delivered_orders"],
        mode="lines",
        name="Delivered Orders",
        line={"color": "#059669", "width": 3},
        yaxis="y2",
    )
)
growth_figure.add_trace(
    go.Scatter(
        x=monthly_market["month"],
        y=monthly_market["orders_trend"],
        mode="lines",
        name="Delivered Orders Regression Trend",
        line={"color": "#6EE7B7", "width": 2, "dash": "dash"},
        yaxis="y2",
    )
)
growth_figure.update_layout(
    title="Monthly GMV and Delivered Orders Growth Trend",
    xaxis={"title": "Month"},
    yaxis={"title": {"text": "GMV (R$)", "font": {"color": "#2563EB"}}, "tickfont": {"color": "#2563EB"}},
    yaxis2={"title": {"text": "Delivered Orders", "font": {"color": "#059669"}}, "tickfont": {"color": "#059669"}, "range": [0, orders_axis_max], "overlaying": "y", "side": "right"},
    template="plotly_white",
    height=550,
    legend={"orientation": "h", "y": 1.12},
    annotations=[
        {"x": monthly_market["month"].iloc[label_index], "y": monthly_market["gmv_trend"].iloc[label_index], "text": f"GMV Trend<br>R² = {gmv_r_squared:.2f}", "showarrow": False, "font": {"color": "#2563EB"}, "yshift": 18},
        {"x": monthly_market["month"].iloc[label_index], "y": monthly_market["orders_trend"].iloc[label_index], "yref": "y2", "text": f"Orders Trend<br>R² = {orders_r_squared:.2f}", "showarrow": False, "font": {"color": "#059669"}, "yshift": -20},
    ],
)
growth_figure.show()

### 5.3 Market Structure and Seller Competition

In [10]:
# Prepare delivered-order item data for GMV market-share analysis
delivered_order_ids = orders_df.loc[orders_df["order_status"].eq("delivered"), "order_id"]
market_items = items_df[items_df["order_id"].isin(delivered_order_ids)].copy()

# Plot product-category market share by GMV
category_share = (
    market_items.merge(products_df[["product_id", "product_category_name"]], on="product_id", how="left")
    .merge(translation_df, on="product_category_name", how="left")
    .assign(category_name=lambda dataframe: dataframe["product_category_name_english"].fillna(dataframe["product_category_name"]).fillna("Unknown"))
    .groupby("category_name", as_index=False)["price"]
    .sum()
    .rename(columns={"price": "gmv"})
    .sort_values("gmv", ascending=False)
)
category_share["market_share"] = category_share["gmv"] / category_share["gmv"].sum()

category_treemap = px.treemap(
    category_share,
    path=["category_name"],
    values="gmv",
    color="gmv",
    color_continuous_scale="Blues",
    custom_data=["market_share"],
    title="Product Category GMV Market Share",
)
category_treemap.update_traces(
    texttemplate="%{label}<br>%{customdata[0]:.1%}",
    hovertemplate="<b>%{label}</b><br>GMV: R$ %{value:,.0f}<br>Market Share: %{customdata[0]:.2%}<extra></extra>",
)
category_treemap.update_layout(height=650, margin={"t": 60, "l": 20, "r": 20, "b": 20})
category_treemap.show()

In [11]:
# Build a product-category Pareto table from delivered-order GMV
category_pareto = category_share.sort_values("gmv", ascending=False).reset_index(drop=True).copy()
category_pareto["cumulative_share"] = category_pareto["gmv"].cumsum() / category_pareto["gmv"].sum()
pareto_80_category_count = int(category_pareto["cumulative_share"].ge(0.80).idxmax() + 1)
pareto_80_category_percentage = pareto_80_category_count / len(category_pareto)

# Plot category GMV and cumulative market share with an 80% reference line
category_pareto_figure = go.Figure()
category_pareto_figure.add_trace(
    go.Bar(
        x=category_pareto["category_name"],
        y=category_pareto["gmv"],
        name="Category GMV",
        marker={"color": "#2563EB"},
        customdata=category_pareto[["market_share"]],
        hovertemplate="<b>%{x}</b><br>GMV: R$ %{y:,.0f}<br>Market Share: %{customdata[0]:.2%}<extra></extra>",
    )
)
category_pareto_figure.add_trace(
    go.Scatter(
        x=category_pareto["category_name"],
        y=category_pareto["cumulative_share"],
        name="Cumulative GMV Share",
        mode="lines",
        line={"color": "#DC2626", "width": 3},
        marker={"size": 6},
        yaxis="y2",
        hovertemplate="<b>%{x}</b><br>Cumulative Share: %{y:.2%}<extra></extra>",
    )
)
category_pareto_figure.update_layout(
    title=f"Product Category GMV Pareto Analysis: {pareto_80_category_percentage:.1%} of Categories Generate 80% of GMV",
    xaxis={"title": "Product Category", "tickangle": -60, "automargin": True},
    yaxis={"title": {"text": "GMV (R$)", "font": {"color": "#2563EB"}}, "tickfont": {"color": "#2563EB"}},
    yaxis2={"title": {"text": "Cumulative GMV Share", "font": {"color": "#DC2626"}}, "tickfont": {"color": "#DC2626"}, "tickformat": ".0%", "range": [0, 1.05], "overlaying": "y", "side": "right"},
    template="plotly_white",
    height=700,
    legend={"orientation": "h", "y": 1.10},
    shapes=[
        {"type": "line", "xref": "paper", "x0": 0, "x1": 1, "yref": "y2", "y0": 0.80, "y1": 0.80, "line": {"color": "#F59E0B", "width": 2, "dash": "dash"}}
    ],
    annotations=[
        {"xref": "paper", "x": 0.99, "yref": "y2", "y": 0.80, "text": "80% Threshold", "showarrow": False, "xanchor": "right", "yanchor": "bottom", "font": {"color": "#B45309"}}
    ],
    margin={"t": 90, "l": 60, "r": 70, "b": 180},
)
category_pareto_figure.show()

**The market exhibits a broadly Pareto-like structure, with approximately 24.3% of product categories generating 80% of total GMV. This indicates that marketplace revenue is concentrated in a relatively small group of core categories, making them priority areas for inventory planning, marketing investment, seller development, and market-entry strategies. However, excessive dependence on these categories may also increase concentration risk.**

### 5.4 Payment Behavior and Consumer Spending

In [12]:
from plotly.subplots import make_subplots

# Exclude undefined payment records from the payment analysis
valid_payments = payments_df.loc[
    payments_df["payment_type"].fillna("").str.lower().ne("not_defined")
].copy()

# Summarize total payment value across all defined payment methods
payment_behavior = (
    valid_payments.groupby("payment_type", as_index=False)["payment_value"]
    .sum()
    .sort_values("payment_value", ascending=False)
)
payment_behavior["payment_method"] = (
    payment_behavior["payment_type"].str.replace("_", " ", regex=False).str.title()
)

# Calculate period-normalized monthly and annual spend per transacting consumer
consumer_payments = (
    valid_payments[["order_id", "payment_value"]]
    .merge(
        orders_df[["order_id", "customer_id", "order_purchase_timestamp"]],
        on="order_id",
        how="inner",
    )
    .merge(
        customers_df[["customer_id", "customer_unique_id"]],
        on="customer_id",
        how="inner",
    )
    .dropna(subset=["customer_unique_id", "order_purchase_timestamp", "payment_value"])
)
consumer_payments["purchase_month"] = consumer_payments["order_purchase_timestamp"].dt.to_period("M")
observed_months = consumer_payments["purchase_month"].nunique()
consumer_total_spend = consumer_payments.groupby("customer_unique_id")["payment_value"].sum()
average_consumer_spend = consumer_total_spend.mean()
average_monthly_consumer_spend = average_consumer_spend / observed_months if observed_months else 0
average_annual_consumer_spend = average_monthly_consumer_spend * 12
consumer_order_counts = consumer_payments.groupby("customer_unique_id")["order_id"].nunique()
repeat_purchase_rate = consumer_order_counts.gt(1).mean()

# Combine the payment-method chart with three vertically stacked consumer indicators
payment_figure = make_subplots(
    rows=3,
    cols=2,
    specs=[
        [{"type": "xy", "rowspan": 3}, {"type": "domain"}],
        [None, {"type": "domain"}],
        [None, {"type": "domain"}],
    ],
    column_widths=[0.68, 0.32],
    row_heights=[1 / 3, 1 / 3, 1 / 3],
    horizontal_spacing=0.12,
    vertical_spacing=0.08,
)

payment_colors = ["#2563EB", "#0F766E", "#F59E0B", "#7C3AED", "#64748B"]
payment_figure.add_trace(
    go.Bar(
        x=payment_behavior["payment_method"],
        y=payment_behavior["payment_value"],
        marker={"color": payment_colors[:len(payment_behavior)]},
        text=payment_behavior["payment_value"],
        texttemplate="R$ %{text:,.0f}",
        textposition="outside",
        cliponaxis=False,
        hovertemplate="<b>%{x}</b><br>Total Payment Value: R$ %{y:,.2f}<extra></extra>",
        showlegend=False,
    ),
    row=1,
    col=1,
)

payment_figure.add_trace(
    go.Indicator(
        mode="number",
        value=average_monthly_consumer_spend,
        number={"prefix": "R$ ", "valueformat": ",.2f", "font": {"size": 38, "color": "#2563EB"}},
        title={"text": "Average Monthly Spend<br>per Consumer", "font": {"size": 16, "color": "#334155"}},
    ),
    row=1,
    col=2,
)
payment_figure.add_trace(
    go.Indicator(
        mode="number",
        value=average_annual_consumer_spend,
        number={"prefix": "R$ ", "valueformat": ",.2f", "font": {"size": 38, "color": "#EA580C"}},
        title={"text": "Annualized Average Spend<br>per Consumer", "font": {"size": 16, "color": "#334155"}},
    ),
    row=2,
    col=2,
)
payment_figure.add_trace(
    go.Indicator(
        mode="number",
        value=repeat_purchase_rate,
        number={"valueformat": ".1%", "font": {"size": 38, "color": "#7C3AED"}},
        title={"text": "Repeat Purchase Rate<br>among Active Consumers", "font": {"size": 16, "color": "#334155"}},
    ),
    row=3,
    col=2,
)

payment_figure.update_layout(
    title="Payment Behavior and Consumer Spending",
    template="plotly_white",
    height=650,
    bargap=0.35,
    margin={"l": 70, "r": 35, "t": 85, "b": 70},
    font={"family": "Arial", "color": "#334155"},
    shapes=[
        {"type": "rect", "xref": "paper", "yref": "paper", "x0": 0.73, "x1": 1.00, "y0": 0.70, "y1": 1.00, "fillcolor": "#EFF6FF", "line": {"width": 0}, "layer": "below"},
        {"type": "rect", "xref": "paper", "yref": "paper", "x0": 0.73, "x1": 1.00, "y0": 0.35, "y1": 0.65, "fillcolor": "#FFF7ED", "line": {"width": 0}, "layer": "below"},
        {"type": "rect", "xref": "paper", "yref": "paper", "x0": 0.73, "x1": 1.00, "y0": 0.00, "y1": 0.30, "fillcolor": "#F5F3FF", "line": {"width": 0}, "layer": "below"},
    ],
)
payment_figure.update_xaxes(title_text="Payment Method", row=1, col=1)
payment_figure.update_yaxes(title_text="Total Payment Value (R$)", tickprefix="R$ ", tickformat=",.0f", rangemode="tozero", row=1, col=1)
payment_figure.show()

## 6. Product and Category Analysis

### 6.1 Category Demand and Sales Mix

### 6.2 Product Pricing and Freight Economics

### 6.3 Product Portfolio and Seller Competitiveness

## 7. Customer Analysis

### 7.1 Customer Base and Purchase Behavior

### 7.2 RFM Segmentation and Repeat Purchasing

### 7.3 Customer Value and Consumption Level

## 8. Regional Market Analysis

### 8.1 Regional Demand and Customer Distribution

### 8.2 State and City Market Comparison

### 8.3 Geographic Opportunity and Logistics Coverage

## 9. Delivery and Logistics Analysis

### 9.1 Delivery Time, Timeliness, and Delays

### 9.2 Freight Cost and Delivery Economics

### 9.3 Order Status and Delivery Exceptions

## 10. Customer Experience and Review Analysis

### 10.1 Review Score Distribution and Satisfaction Levels

### 10.2 Review Drivers and Low-Score Order Analysis

## 11. China-to-Brazil Market Entry Analysis

### 11.1 Market Opportunity and Target Segments

### 11.2 Category Selection and Product Positioning

### 11.3 Regional Entry and Logistics Design

### 11.4 Payment, Service, and Localization Considerations

## 12. Key Findings

## 13. Business Recommendations

## 14. Analysis Limitations

## 15. Conclusion

## 16. Appendix